name: Docker CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      run: | 
        docker build --platform linux --tag ricardoprograming161/cicdtest:latest -f .
    - name: Publish docker image
      run: |
        docker push ricardoprograming161/cicdtest:latest
    - name: App service auth
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ricardowebapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ricardoprograming161/cicdtest:latest'